import BusinessSignup from "@/components/businessSignup/BusinessSignup";
import Home from "@/components/home";
import Head from "next/head";

const BusinessSignUpPage = () => (
  <>
    <Head>
      <title>EWN Business SignUp Page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <BusinessSignup />
  </>
);

export default BusinessSignUpPage;
