import BusinessSignup from "@/components/businessSignup";
import Head from "next/head";

const IndividualSignUpPage = () => (
  <>
    <Head>
      <title>EWN Individual SignUp Page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <BusinessSignup />
  </>
);

export default IndividualSignUpPage;
