import Signup from "@/components/signup";
import Head from "next/head";

const SignupPage = () => (
  <>
    <Head>
      <title>EWN Sign Up</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Signup />
  </>
);

export default SignupPage;
